export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGING_FALUIRE = 'LOGING_FALUIRE';

export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';

export const SET_STATES_FALSE = 'SET_STATES_FALSE';

export const SET_PLANS_DATA = 'SET_PLANS_DATA';

export const CHECK_SUBSCRIPTION_STATE = 'CHECK_SUBSCRIPTION_STATE';
