# Generated by Django 2.2.27 on 2022-03-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
