# Generated by Django 2.2.27 on 2022-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_category_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='screen_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
