# Generated by Django 2.2.28 on 2023-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='eventaddmoretext',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
