# Generated by Django 2.2.28 on 2023-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20230110_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventaddmoretext',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='events/images'),
        ),
    ]
