# Generated by Django 2.2.28 on 2023-01-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20230110_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventaddmoretext',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
