export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FALUIRE = 'UPDATE_PROFILE_FALUIRE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FALUIRE = 'GET_PROFILE_FALUIRE';

export const PROFILE_EVENT_REQUEST = 'PROFILE_EVENT_REQUEST';
export const PROFILE_EVENT_SUCCESS = 'PROFILE_EVENT_SUCCESS';
export const PROFILE_EVENT_FALUIRE = 'PROFILE_EVENT_FALUIRE';

// export const DELETEACCOUNT_REQUEST = 'DELETEACCOUNT_REQUEST';
// export const DELETEACCOUNT_SUCCESS = 'DELETEACCOUNT_SUCCESS';
// export const DELETEACCOUNT_FALUIRE = 'DELETEACCOUNT_FALUIRE';
