export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FALUIRE = 'REGISTER_FALUIRE';

export const RESET_SIGNUP = 'RESET_SIGNUP';

export const CREATE_STRIPE_CUSTOMER_REQUEST = 'CREATE_STRIPE_CUSTOMER_REQUEST';
export const CREATE_STRIPE_CUSTOMER_SUCCESS = 'CREATE_STRIPE_CUSTOMER_SUCCESS';
export const CREATE_STRIPE_CUSTOMER_FALUIRE = 'CREATE_STRIPE_CUSTOMER_FALUIRE';
