export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGING_FALUIRE = 'LOGING_FALUIRE';

export const LOGIN_VIA_FACEBOOK_REQUEST = 'LOGIN_VIA_FACEBOOK_REQUEST';
export const LOGIN_VIA_FACEBOOK_SUCCESS = 'LOGIN_VIA_FACEBOOK_SUCCESS';
export const LOGIN_VIA_FACEBOOK_FALUIRE = 'LOGIN_VIA_FACEBOOK_FALUIRE';

export const LOGIN_VIA_GMAIL_REQUEST = 'LOGIN_VIA_GMAIL_REQUEST';
export const LOGIN_VIA_GMAIL_SUCCESS = 'LOGIN_VIA_GMAIL_SUCCESS';
export const LOGIN_VIA_GMAIL_FALUIRE = 'LOGIN_VIA_GMAIL_FALUIRE';

export const LOGIN_VIA_APPLE_REQUEST = 'LOGIN_VIA_APPLE_REQUEST';
export const LOGIN_VIA_APPLE_SUCCESS = 'LOGIN_VIA_APPLE_SUCCESS';
export const LOGIN_VIA_APPLE_FALUIRE = 'LOGIN_VIA_APPLE_FALUIRE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FALUIRE = 'FORGOT_PASSWORD_FALUIRE';

export const RESEND_FORGOT_PASSWORD = 'RESEND_FORGOT_PASSWORD';
export const RESEND_FORGOT_PASSWORD_SUCCESS = 'RESEND_FORGOT_PASSWORD_SUCCESS';
export const RESEND_FORGOT_PASSWORD_FALUIRE = 'RESEND_FORGOT_PASSWORD_FALUIRE';

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FALUIRE = 'GET_TOKEN_FALUIRE';

export const RESET_PASS_REQUEST = 'RESET_PASS_REQUEST';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FALUIRE = 'RESET_PASS_FALUIRE';

export const DOTS_SECONDS = 'DOTS_SECONDS';
export const DOTS_SECONDS_RESET = 'DOTS_SECONDS_RESET';
export const RESET_ERRORS = 'RESET_ERRORS';

export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_ACCESS_TOKEN_SUCCESS = 'GET_ACCESS_TOKEN_SUCCESS';
export const GET_ACCESS_TOKEN_FALUIRE = 'GET_ACCESS_TOKEN_FALUIRE';
