version: "3"

services:
  web:
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12
  redis:
    image: redis:5

  celery:
    build:
      context: .
    env_file: .env
    user: django
    command: celery -A ideapros_llc_passag_30831 worker --beat --scheduler django -l info --concurrency 2
    depends_on:
      - web
      - postgres
      - redis
