export const CONTENT_EVENT_REQUEST = 'CONTENT_EVENT_REQUEST';
export const CONTENT_EVENT_SUCCESS = 'CONTENT_EVENT_SUCCESS';
export const CONTENT_EVENT_FALUIRE = 'CONTENT_EVENT_FALUIRE';

export const CONTENT_DELETE_EVENT_REQUEST = 'CONTENT_DELETE_EVENT_REQUEST';
export const CONTENT_DELETE_EVENT_SUCCESS = 'CONTENT_DELETE_EVENT_SUCCESS';
export const CONTENT_DELETE_EVENT_FALUIRE = 'CONTENT_DELETE_EVENT_FALUIRE';