export const DELETEACCOUNT_REQUEST = 'DELETEACCOUNT_REQUEST';
export const DELETEACCOUNT_SUCCESS = 'DELETEACCOUNT_SUCCESS';
export const DELETEACCOUNT_FALUIRE = 'DELETEACCOUNT_FALUIRE';

export const REQUEST_CHANGE_PASSWORD = 'REQUEST_CHANGE_PASSWORD';
export const REQUEST_CHANGE_PASSWORD_SUCCESS = 'REQUEST_CHANGE_PASSWORD_SUCCESS';
export const REQUEST_CHANGE_PASSWORD_FAILURE = 'REQUEST_CHANGE_PASSWORD_FAILURE';
export const RESET = 'RESET';


export const SIGN_OUT = 'SIGN_OUT';
