export default {
  logos: require('src/assets/images/logos.png'),
  loginbg: require('src/assets/images/loginbg.png'),
  instagram: require('src/assets/images/instagram.png'),
  pass: require('src/assets/images/pass.png'),
  age: require('src/assets/images/age.png'),
  sex: require('src/assets/images/sex.png'),
  relation: require('src/assets/images/relation.png'),
  child: require('src/assets/images/child.png'),
  profession: require('src/assets/images/profession.png'),
  userImg: require('src/assets/images/userImg.png'),
  email: require('src/assets/images/email.png'),
  splash: require('src/assets/images/splash.png'),
  leftAeroLight: require('src/assets/images/leftAeroLight.png'),
  BackAeroLight: require('src/assets/images/BackAeroLight.png'),
  SignOut: require('src/assets/images/SignOut.png'),
  Delete: require('src/assets/images/Delete.png'),
  Deletew: require('src/assets/images/Deletew.png'),
  nopic: require('src/assets/images/nopic.png'),
  splish1: require('src/assets/images/splish1.png'),
  record: require('src/assets/images/record.png'),
  refresh: require('src/assets/images/refresh.png'),
  backArrows: require('src/assets/images/backArrows.png'),
  backbtn: require('src/assets/images/backbtn.png'),
  apple: require('src/assets/images/apple.png'),
  facebook: require('src/assets/images/facebook.png'),
  google: require('src/assets/images/google.png'),
  brooke: require('src/assets/images/brooke.png'),
  gifts: require('src/assets/images/gifts.png'),
  daniel: require('src/assets/images/daniel.png'),
  khad: require('src/assets/images/khad.png'),
  lucas: require('src/assets/images/lucas.png'),
  party: require('src/assets/images/party.png'),
  invitedColaburater: require('src/assets/images/invitedColaburater.png'),

  userImage: require('src/assets/images/user.png'),
  headerProfile: require('src/assets/images/headerProfile .png'),
  cover: require('src/assets/images/cover.png'),
  profileImg: require('src/assets/images/profileImg.png'),

  inviteImage1: require('src/assets/images/inviteImage1.png'),
  inviteImg2: require('src/assets/images/inviteImg2.png'),
  myImage1: require('src/assets/images/myImage1.png'),
  myImage2: require('src/assets/images/myImage2.png'),

  enterTitle: require('src/assets/images/enterTitle.png'),

  date: require('src/assets/images/date.png'),

  // CreateLifeStory screen images
  Vector: require('src/assets/images/Vector.png'),
  downAero: require('src/assets/images/downAero.png'),
  star: require('src/assets/images/star.png'),
  time: require('src/assets/images/time.png'),
  cvvNumber: require('src/assets/images/cvvNumber.png'),

  emailImage: require('src/assets/images/email.png'),
  paswordImage: require('src/assets/images/password.png'),
  lifeStory: require('src/assets/images/lifeStory.png'),
  confirmImage: require('src/assets/images/confirm.png'),
  codeImage: require('src/assets/images/code.png'),
  editProfile: require('src/assets/images/editProfile.png'),
  myContent: require('src/assets/images/myContent.png'),
  myVault: require('src/assets/images/myVault.png'),
  add: require('src/assets/images/Add.png'),
  backArrowImage: require('src/assets/images/backArrow.png'),
  darkBackArrow: require('src/assets/images/darkBackArrow.png'),
  darkPass: require('src/assets/images/darkPass.png'),

  facebookImage: require('src/assets/images/facebook.png'),
  appleImage: require('src/assets/images/apple.png'),
  applePay: require('src/assets/images/applepay.png'),
  tickImage: require('src/assets/images/tick.png'),
  tickWhite: require('src/assets/images/tickWhite.png'),
  dotWhite: require('src/assets/images/dotWhite.png'),
  dot: require('src/assets/images/dot.png'),
  fpassword: require('src/assets/images/fpassword.png'),
  femail: require('src/assets/images/femail.png'),
  fcode: require('src/assets/images/fcode.png'),
  play: require('src/assets/images/play.png'),
  photos: require('src/assets/images/photos.png'),
  feye: require('src/assets/images/feye.png'),
  fconfirm: require('src/assets/images/fconfirm.png'),
  password: require('src/assets/images/password.png'),
  eye: require('src/assets/images/eye.png'),
  eyehide: require('src/assets/images/eyehide.png'),
  eyew: require('src/assets/images/eyew.png'),
  calender: require('src/assets/images/calender.png'),
  cardNumber: require('src/assets/images/cardNumber.png'),

  home: require('src/assets/images/home.png'),
  content: require('src/assets/images/content.png'),
  gift: require('src/assets/images/gift.png'),
  cart: require('src/assets/images/cart.png'),
  setting: require('src/assets/images/setting.png'),

  home1: require('src/assets/images/home1.png'),
  content1: require('src/assets/images/content1.png'),
  gift1: require('src/assets/images/gift1.png'),
  cart1: require('src/assets/images/cart1.png'),
  setting1: require('src/assets/images/setting1.png'),
};
