# Generated by Django 2.2.27 on 2022-08-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_storageallowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageallowed',
            options={'verbose_name': 'Storage Allowed', 'verbose_name_plural': 'Storage Allowed'},
        ),
    ]
