export const GET_CARD_REQUEST = "GET_CARD_REQUEST"
export const GET_CARD_SUCCESS = "GET_CARD_SUCCESS"
export const GET_CARD_FALUIRE= "GET_CARD_FALUIRE"

export const CANCEL_SUBSCRIPTION_REQUEST = "CANCEL_SUBSCRIPTION_REQUEST" 
export const CANCEL_SUBSCRIPTION_SUCCESS = "CANCEL_SUBSCRIPTION_SUCCESS" 
export const CANCEL_SUBSCRIPTION_FAILURE = "CANCEL_SUBSCRIPTION_FAILURE"

export const GET_SUBSCRIPTION_LIST_REQUEST = "GET_SUBSCRIPTION_LIST_REQUEST"
export const GET_SUBSCRIPTION_LIST_SUCCESS = "GET_SUBSCRIPTION_LIST_SUCCESS"
export const GET_SUBSCRIPTION_LIST_FAILURE= "GET_SUBSCRIPTION_LIST_FAILURE"
