export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';

export const CREATE_SUBSCRIPTION_REQUEST = 'CREATE_SUBSCRIPTION_REQUEST';
export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_FAILURE = 'CREATE_SUBSCRIPTION_FAILURE';

export const DISCOUNT_REQUEST = 'DISCOUNT_REQUEST';
export const DISCOUNT_REQUEST_SUCCESS = 'DISCOUNT_REQUEST_SUCCESS';
export const DISCOUNT_REQUEST_FAILURE = 'DISCOUNT_REQUEST_FAILURE';
