export const GET_SUBSCRIPTION_LIST = 'GET_SUBSCRIPTION_LIST';
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS';
export const GET_SUBSCRIPTION_FAILURE = 'GET_SUBSCRIPTION_FAILURE';

export const GET_PLANS_LIST = 'GET_PLANS_LIST';
export const GET_PLANS_LIST_SUCCESS = 'GET_PLANS_LIST_SUCCESS';
export const GET_PLANS_LIST_FAILURE = 'GET_PLANS_LIST_FAILURE';
