export const LIFESTORY_REQUEST = 'LIFESTORY_REQUEST';
export const LIFESTORY_SUCCESS = 'LIFESTORY_SUCCESS';
export const LIFESTORY_FALUIRE = 'LIFESTORY_FALUIRE';

export const GET_LIFESTORY_REQUEST = 'GET_LIFESTORY_REQUEST';
export const GET_LIFESTORY_SUCCESS = 'GET_LIFESTORY_SUCCESS';
export const GET_LIFESTORY_FALUIRE = 'GET_LIFESTORY_FALUIRE';

export const EDIT_LIFESTORY_REQUEST = 'EDIT_LIFESTORY_REQUEST';
export const EDIT_LIFESTORY_SUCCESS = 'EDIT_LIFESTORY_SUCCESS';
export const EDIT_LIFESTORY_FALUIRE = 'EDIT_LIFESTORY_FALUIRE';
