export const LISTCARD_REQUEST = 'LISTCARD_REQUEST';
export const LISTCARD_SUCCESS = 'LISTCARD_SUCCESS';
export const LISTCARD_FALUIRE = 'LISTCARD_FALUIRE';

export const DELETECARD_REQUEST = 'DELETECARD_REQUEST';
export const DELETECARD_SUCCESS = 'DELETECARD_SUCCESS';
export const DELETECARD_FALUIRE = 'DELETECARD_FALUIRE';

export const PAYMENTS_REQUEST = 'PAYMENTS_REQUEST';
export const PAYMENTS_SUCCESS = 'PAYMENTS_SUCCESS';
export const PAYMENTS_FALUIRE = 'PAYMENTS_FALUIRE';
